export default {
    // speicial document/ layer
    '### Active Document ###': '### 当前文档 ###',
    '### The Canvas ###': '### 整个画布 ###',
    '### New Layer ###': '### 新图层 ###',
    '### Selected Layer ###': '### 所选图层 ###',
    '### Keep Size or Fit Canvas ###': '### 保持尺寸或适应画布 ###',
    '_SDPPP_PSD_': '_SDPPP_PSD_',

    // A1111 UI
    'Save and run immediately': '保存并立即执行',
    'Close': '关闭',
    'Select a {0}': `选择一个 {0}`,

    // comfyui dialog
    'How to use .ccx file': '如何使用 .ccx 文件',
    '1. If you have installed Adobe Creative Cloud': '1. 如果你已经安装了 Adobe Creative Cloud', 
    'Just double click the .ccx file, it will install the plugin automatically': '双击 .ccx 文件，它会自动安装',
    "2. If you don't have Adobe Creative Cloud": '2. 如果你没有 Adobe Creative Cloud',
    'Rename .ccx to .zip and extract it into ': '将 .ccx 重命名为 .zip 并解压到',
    'or': '或',
    'Photoshop directory': 'Photoshop 安装目录',

    // comfyui error
    'Cannot connect multiple different document widgets with same value': '不能连接多个具有相同值的文档小部件',
    'You can only have one SDPPP Settings node in a workflow': '一个工作流中只能有一个 SDPPP Settings 节点',
    'convert widget {0} failed:': '控件{0}转换失败：',
    'hidden webview load failed: {0}, please select a browser page to continue': '内置 webview 加载失败: {0}，请选择一个浏览器页面继续',
    
    // comfy node title
    'SDPPP Get Document': '获取文档(GetDocument)',
    'SDPPP Get Layer By ID': '获取图层(GetLayer)',
    'SDPPP Get Linked Layers': '获取链接图层(GetLinkedLayers)',
    'SDPPP Get Layers In Group': '获取组中图层(GetLayersInGroup)',
    'SDPPP Get Text From Layer': '获取图层文本(GetTextFromLayer)',
    'SDPPP Parse Layer Info': '解析图层信息(ParseLayerInfo)',
    'SDPPP Get Selection': '获取选区(GetSelection)', 
    'SDPPP Get Image From Photoshop': '从PS获取图像(GetImageFromPhotoshop)',
    'SDPPP Send Images To Photoshop': '发送图像到PS(SendImagesToPhotoshop)',
    'SDPPP Send Text To Layer': '发送文本到图层(SendTextToLayer)',
    'SDPPP Select Layer And Run PS Action': '选中图层并运行PS Action(RunPhotoshopAction)',

// comfy widget/input
    'download PS plugin (.ccx)': '下载 Photoshop 插件 (.ccx)',
    'current ComfyUI pageid: {0}': '当前 ComfyUI 页面ID: {0}',
    'current A1111 pageid: {0}': '当前 A1111 页面ID: {0}',
    'document linked': '文档参数已链接',
    'layer linked': '图层参数已链接',
    'bound linked': '范围参数已链接',
    'document': '文档', 
    'Document': '文档', 
    'DOCUMENT': '文档', 
    'document_name': '文档名字id',
    'layer_nameid': '图层名字id',
    'layer_name': '图层名字',
    'layer_info': '图层信息',
    'bound_top': '范围上边距',
    'bound_left': '范围左边距',
    'bound_width': '范围宽度',
    'bound_height': '范围高度',
    'center_x': '中心点x',
    'center_y': '中心点y',
    'opacity': '透明度',
    'layer': '图层',
    'layer_or_group': '图层(或组)',
    'Layer_or_group': '图层(或组)',
    'bound': '范围',
    'bounds': '范围',
    'bounds [optional]': '范围[可选]',
    'boundary': '范围',
    'Boundary': '范围',
    'canvas_boundary': '画布范围',
    'canvas_bound': '画布范围',
    'layer_boundary': '图层范围',
    'layer_bound': '图层范围',
    "Photoshop Disconnected!" : "Photoshop 未连接！",
    'rgb_out': 'RGB输出',
    'alpha_out': 'Alpha输出',
    'images': '图像',
    'text': '文本',
    'ID_mode': '精确ID模式',
    'name_mode': '名字匹配模式',
    'select': '选择',
    'document boundary': '文档范围',
    'layer boundary': '图层范围',
    'selection boundary': '选中范围',
    'save .psd to this workflow': '保存.psd到这个工作流',
    'extract saved .psd to Photoshop': '提取保存的.psd到Photoshop',
    'sample .psd': '示例.psd',
    'mask': '遮罩',
    'name': '名称',
    'quality': '图像质量',
    'action_set': '动作组',
    'action': '动作',
    
    // photoshop UI
    'Runner': '运行载体',
    'PS Webview': 'PS 内置网页',
    'Browser {0}': '浏览器页面 {0}',
    'timeout': '超时',
    'Loading...': '加载中...',
    '--multi-user Not Login!': '--multi-user已激活，但未登录！',
    'Logout': '登出',
    'User: ': '用户: ',
    'connect': '连接',
    'connected': '已连接',
    'disconnect': '断开',
    'disconnected': '已断开连接',
    'reconnecting...': '重连中...',  
    'connecting': '连接中',  
    'webpages': '网页列表',
    'workflows': '工作流',
    'workflow': '工作流',
    'auto run page [{0}] after change..': '更改后自动运行页面 {0}..',
    'auto run workflow [{0}] after change..': '更改后自动运行工作流 {0}..',
    'auto run workflow after change..': '更改后自动运行工作流..',
    'selection_only': '仅选区',
    'Queue:': '队列:',
    'Set As:': '设置为:',
    'Error {0}... please contact me via Discord/Github': '出现错误 {0}...，请通过 QQ/Github 联系我',
    'Webview initialize failed. Please report to me via Discord/Github with your ComfyURL, Operate System': 'Webview 初始化失败，请通过 QQ/Github 联系我并附上你的Comfy地址、操作系统',
    'ComfyUI with --multi-user is only available for sponsors': '带"--multi-user"的ComfyUI仅对赞助者开放',
    'Workflow Runner is loading...': '运行载体尚在加载...',
    '(Page ID: {0})Queue: {1}': '(页面ID: {0}) 队列长度 {1}',
    'no suitable node to control in this workflow': '这个工作流中没有能控制的节点',
    "Save": "保存",
    "Edit": "编辑",
    "Edit in ComfyUI": "在 ComfyUI 中编辑",
    "using browser page [{0}] for workflow running": '正接管网页 [{0}] 运行工作流',
    'workflow running by hidden webview': '工作流在隐藏的webview中运行',
    'Lock Image': '锁定图像',
    'Unlock Image': '解锁图像',
    'search...': '搜索...',
    'disabled when running in browser page': '接管网页时不可用',
    'only supported in Photoshop': '仅在 Photoshop 中支持',
    'Login': '登录',
    'Invitation Code': '邀请码',
    'Username': '用户名',
    'Password': '密码',
    'Please input invitation code': '请输入邀请码',
    'Please input username': '请输入用户名',
    'Please input password': '请输入密码',
    'Open more ComfyUI pages to see more options here': '打开更多 ComfyUI 页面以查看更多选项',
    'Comfy multi-user: ': 'Comfy 多用户: ',
    'Not Login': '未登录',
    'Comfy API-Key: ': 'Comfy API-Key: ',
    'Login/Auth': '登录/认证',
    'Logged in by email/password': '已通过邮箱/密码登录',
    'Set API Key': '设置 API Key',
    'Please input API key (will reload Runner)': '请输入 API Key (会重启运行载体)',
    '### Active Workflow ###': '### 当前工作流 ###',
    '### Example SDXL ###': '### 示例SDXL工作流 ###',
    'Open ComfyUI in the browser to see more options': '在浏览器中打开 ComfyUI 以得到更多选项',
    'Webview load timeout, please switch to a different runner': 'Webview 加载超时，请切换到其他运行载体',
    'Save workflow to ComfyUI': '保存工作流到 ComfyUI',
    'Reload workflow': '重新加载工作流',
    'Stop and cancel all': '停止并取消所有',
    'Start auto running after change': '更改后自动运行',
    'Stop auto run': '停止自动运行',
    'Run workflow': '运行工作流',
    'Run workflow xN': '运行工作流N次',
    'Back to workflow list': '返回工作流列表',

    // photoshop connect error
    '502: Maybe the server is not running': '502: 服务器可能未运行',
    '404: Maybe SDPPP is not installed or failed to run in ComfyUI': '404: 可能在ComfyUI中SDPPP未安装或运行失败',
    '{0}. reconnecting...': '{0}. 重连中...',
    'disconnected to {0} failed {1}': `断开连接 {0} 错误 {1}`,
    'version mismatch, please reinstall PS plugin': '版本不匹配，请重新安装 PS 插件',
    'instance type not recognized': '未识别的软件类型',
    'Error: {0}': '错误: {0}',
    'Verification Error': '验证错误',

    // photoshop event error
    'document {0} not found': '找不到文档: {0}',
    'only layer kind "TEXT" is supported, invalid layer: {0}': '不支持非文本图层: {0}',
    'create layer failed': '创建图层失败',
    'layer not found {0}': '找不到图层: {0}',
    'no linked layer for {0}': '没有链接图层: {0}',
    'layer {0} is not a group': '图层 {0} 不是一个组',
    'no layer in group {0}': '组 {0} 中没有图层',
    'layer not found: {0}': '找不到图层: {0}',
    'No upload_name': '上传接口返回了失败',
    'get pixel of {0} failed': '获取像素失败: {0}',
    'merge group failed': '合并组失败',
    'invalid name: {0}': '非法的名称: {0}',
    'get_layer_info: layer_identify required': 'get_layer_info: 需要 layer_identify',
    'invalid action: {0}': '无效的操作: {0}',
    'create document failed': '创建文档失败',
    'create document for preview': '创建预览文档',
    'resize document for preview': '调整预览文档尺寸',
    'no first related layer in {0}': '组 {0} 中没有第一个相关图层',
    "imageDataError: data length is not multiple of width * height": "图像数据有误: 数据长度不是宽度 * 高度的倍数",
    "imageDataError: originComponents must be 1 or 3": "图像数据有误: originComponents 必须是 1 或 3",
    'unexpected connection lost, please try to reconnect': '意外断开连接，请尝试重新连接',
    "Workflow list is empty, please save a workflow by Comfy's lastest UI": '工作流列表为空，请在Comfy的新版UI中保存一个工作流',
    'No opened ComfyUI pages': '没有已打开的ComfyUI页面',
    'comfyAPI is not initialized, maybe comfyUI is too old': '无法获取 ComfyAPI，可能 ComfyUI 版本太旧',
    'unsupported channel counts: {0}': '不支持的通道数: {0}',
    'Timeout, Maybe the URL is wrong': '超时，可能 comfy地址 填写错误',
    'Workflow list loading failed: {0}': '工作流列表加载失败: {0}',
    'Please register a user in ComfyUI': '请在 ComfyUI 中注册一个用户',
    'GetSelection need Photoshop version 25+': 'GetSelection 需要 Photoshop 25+ 版本',
    'Action {0} not found': 'Action {0} 未找到',
    'Action set {0} not found': 'ActionSet {0} 未找到',
    '{0} cannot be used in Photoshop Action Node': '{0} 不能在 Photoshop Action 节点中使用',
    'Group layers': '图层组',
    'Show All Groups': '显示所有组',

    // photoshop modal state
    'create document for sent images': '给发送的图片创建文档',
    'show sent images': '显示发送的图片',
    'fallback show sent images': '取消显示发送的图片',
    "get content of layer {0}": "获取图层 {0} 的内容",
    'fallback get content of layer {0}': '取消获取图层 {0} 的内容',
    'get layer info': '获取图层信息',
    'sdppp extract PSD': 'sdppp 导入 PSD',
    'sdppp get PSD': 'sdppp 获取 PSD', 
    'set text to layer': '设置图层的文本',
    'run Photoshop Action': 'sdppp 运行 Photoshop Action',
    'select layer': 'sdppp 选中图层',
    
    // photoshop dialog/widget
    '{0} wants to extract a PSD file to Photoshop, are you sure?': '{0} 想要释放一个.psd文件到Photoshop，确定吗？',
    'should sdppp refuse extracting PSD to Photoshop in this session anymore?': '是否要让 sdppp 拒绝本次PS会话再次接受.psd释放请求？',
    'Wide Mode': '宽屏模式',
    'Quick Set': '快速设置',
    'Selected Layer': '选中图层',
    'Selected Layer (invert)': '选中图层(反向)',
    'Canvas': '画布',
    'Selection': '选区',
    'Manual': '手动模式',
    'Auto': '自动模式',

    // about
    'This plugin is based on sd-ppp': '本插件基于sd-ppp开发',
    'And follows its open source license:': '并遵循其开源协议：',
    "Cloud": "云端推荐",
    "Sponsors": "赞助",
    "waiting...": '虚位以待',
    'Links': '友情链接',
    'Community': '社区',
    'LICENSE:': '许可证：',
    'Official Site': '官方网站',

    // comfy popup
    "upload": "上传",
    "Simplify Workflow": "简化工作流",
    "Photoshop": "Photoshop",
    "Photoshop plugin settings": "Photoshop 插件设置",
    "Photoshop plugin": "Photoshop 插件",
    "SDPPP Settings/Misc": "SDPPP 设置/杂项",
    "Sample .PSD for this workflow:": "示例.PSD",
    "Download Example .PSD": "下载示例.PSD",
    "Maximum Image Size (px):": "最大图像尺寸(px)",
    "Download": "下载",
    "Upload": "上传",
    "Reset": "重置",
    'Refresh': '刷新',
    'Comfy URL (You can copy it to connect ComfyUI in the plugin):': 'Comfy地址(你可以复制它到插件中连接ComfyUI):',
    'use slider for number widget:': '数字控件使用滑块',
    'Photoshop is not connected': 'Photoshop 未连接',
    'select...': '请选择',
    'click to edit': '点击编辑',

    // comfy call error
    'ComfyManager not found, cannot reboot': 'Comfy Manager未安装，无法重启',
    'Failed to reboot ComfyUI': '重启ComfyUI失败',
}
